apiVersion: v1
kind: Service
metadata:
  name: kube-fe-lb
  namespace: test-kube-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kube-fe
