apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-fe-depl
  namespace: test-kube-app
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kube-fe
  template:
    metadata:
      labels:
        app: kube-fe
    spec:
      containers:
        - image: grigorydocker/test-kube-fe:1.0.7
          imagePullPolicy: Always
          name: kube-fe-cont
          ports:
            - containerPort: 80
